export const GET_LIST = 'GET_LIST'
export const SET_LIST = 'SET_LIST'
export const SET_AUDIO = 'SET_AUDIO'
export const SET_MUSIC_URL = 'SET_MUSIC_URL'
export const SET_PLAYING_TITLE = 'SET_PLAYING_TITLE'
export const INIT_PLAYING_STATE = 'INIT_PLAYING_STATE'