export const GET_LIST = 'GET_LIST'
export const SET_LIST = 'SET_LIST'
export const SET_AUDIO = 'SET_AUDIO'
export const SET_MUSIC_URL = 'SET_MUSIC_URL'
export const SET_PLAYING_TITLE = 'SET_PLAYING_TITLE'
export const INIT_PLAYING_STATE = 'INIT_PLAYING_STATE'

export const SAVE_SCROLL_DIS = 'SAVE_SCROLL_DIS'
export const SET_PLAY_LIST = 'SET_PLAY_LIST'
export const UPDATE_PLAY_NUMBER = 'UPDATE_PLAY_NUMBER'

export const AJAX_POST = 'AJAX_POST'
export const LOADING_SWITCH = 'LOADING_SWITCH'
export const COUNT_POST_NUMBER = 'COUNT_POST_NUMBER'

export const CHANGE_PLAY_STATUS = 'CHANGE_PLAY_STATUS'
export const GET_SONG_LIST = 'GET_SONG_LIST'

export const SET_PLAYING_LIST = "SET_PLAYING_LIST"
export const UPDATE_LIST_ID = "UPDATE_LIST_ID"

export const UPDATE_SINGER_LIST = "UPDATE_SINGER_LIST"
